/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.riskgame.gui;

/**
 *
 * @author elifnur
 */
public class EndFrame extends javax.swing.JFrame {

    /**
     * Creates new form EndFrame
     */
    public EndFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(152, 58, 52));
        jButton1.setFont(new java.awt.Font("Apple LiSung", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 245, 204));
        jButton1.setText("PLAY AGAIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 430, 250, -1));

        jButton2.setBackground(new java.awt.Color(152, 58, 52));
        jButton2.setFont(new java.awt.Font("Apple LiSung", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(253, 245, 204));
        jButton2.setText("END GAME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 220, -1));

        jLabel2.setBackground(new java.awt.Color(253, 245, 204));
        jLabel2.setFont(new java.awt.Font("Apple LiSung", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 58, 52));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/endscreen.png"))); // NOI18N
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (replayAction != null) {
            replayAction.run();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (exitAction != null) {
            exitAction.run();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private Runnable replayAction;
    private Runnable exitAction;

    public void setWinner(String winnerName) {
        jLabel2.setText(winnerName + " WINS!");
    }

    public void setReplayAction(Runnable replayAction) {
        this.replayAction = replayAction;
    }

    public void setExitAction(Runnable exitAction) {
        this.exitAction = exitAction;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
