/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.riskgame.gui;

import com.mycompany.riskgame.game.GamePhase;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author elifnur
 */
public class GameFrame extends javax.swing.JFrame {

    private java.io.PrintWriter out;
    private GamePhase currentPhase = GamePhase.WAITING_FOR_PLAYERS;
    private int remainingDraftTroops = 0;
    private String fromTerritory = null;
    private String toTerritory = null;
    private String selectedTerritory;
    private String currentPlayer = "NONE";
    private String currentTurnPlayer = "NONE";
    private Map<String, String> territoryOwners = new HashMap<>();

    private Map<String, Integer> troopCounts = new HashMap<>();
    private Map<String, javax.swing.JButton> territoryButtons = new HashMap<>();
    private Map<String, java.awt.Color> playerColors = new HashMap<>();

    private java.awt.Color[] defaultColors = {
        new java.awt.Color(100, 200, 255),
        new java.awt.Color(255, 150, 150)
    };

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        setupButtonMap();
        diceLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        territoryButton1 = new javax.swing.JButton();
        territoryButton2 = new javax.swing.JButton();
        territoryButton3 = new javax.swing.JButton();
        territoryButton4 = new javax.swing.JButton();
        territoryButton5 = new javax.swing.JButton();
        territoryButton6 = new javax.swing.JButton();
        territoryButton7 = new javax.swing.JButton();
        territoryButton8 = new javax.swing.JButton();
        territoryButton9 = new javax.swing.JButton();
        territoryButton10 = new javax.swing.JButton();
        territoryButton11 = new javax.swing.JButton();
        territoryButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameLogArea = new javax.swing.JTextArea();
        actionButton = new javax.swing.JButton();
        diceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        territoryButton1.setText("Olympus");
        territoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 140));

        territoryButton2.setText("Sparta");
        territoryButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 140));

        territoryButton3.setText("Athens");
        territoryButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 140));

        territoryButton4.setText("Delphi");
        territoryButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 250, 60));

        territoryButton5.setText("Arcadia");
        territoryButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 80, 140));

        territoryButton6.setText("Troy");
        territoryButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 140));

        territoryButton7.setText("Elysium");
        territoryButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, -1, 140));

        territoryButton8.setText("Mycenae");
        territoryButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, 140));

        territoryButton9.setText("Rhodes");
        territoryButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 140, 80, 160));

        territoryButton10.setText("Corinth");
        territoryButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 190, 60));

        territoryButton11.setText("Crete");
        territoryButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 80, 160));

        territoryButton12.setText("Olympia");
        territoryButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, 200));

        statusArea.setColumns(20);
        statusArea.setRows(5);
        jScrollPane1.setViewportView(statusArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 360, 120));

        gameLogArea.setColumns(20);
        gameLogArea.setRows(5);
        jScrollPane2.setViewportView(gameLogArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 360, 110));

        actionButton.setText("Waiting");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(actionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 440, 210, 50));

        diceLabel.setText("Attacker: [6, 5, 2]\nDefender: [4, 3]");
        jPanel1.add(diceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 310, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void territoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton1ActionPerformed
        handleTerritoryClick("Olympus");
    }//GEN-LAST:event_territoryButton1ActionPerformed

    private void territoryButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton2ActionPerformed
        handleTerritoryClick("Sparta");
    }//GEN-LAST:event_territoryButton2ActionPerformed

    private void territoryButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton3ActionPerformed
        handleTerritoryClick("Athens");
    }//GEN-LAST:event_territoryButton3ActionPerformed

    private void territoryButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton4ActionPerformed
        handleTerritoryClick("Delphi");
    }//GEN-LAST:event_territoryButton4ActionPerformed

    private void territoryButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton5ActionPerformed
        handleTerritoryClick("Arcadia");
    }//GEN-LAST:event_territoryButton5ActionPerformed

    private void territoryButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton6ActionPerformed
        handleTerritoryClick("Troy");
    }//GEN-LAST:event_territoryButton6ActionPerformed

    private void territoryButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton7ActionPerformed
        handleTerritoryClick("Elysium");
    }//GEN-LAST:event_territoryButton7ActionPerformed

    private void territoryButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton8ActionPerformed
        handleTerritoryClick("Mycenae");
    }//GEN-LAST:event_territoryButton8ActionPerformed

    private void territoryButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton9ActionPerformed
        handleTerritoryClick("Rhodes");
    }//GEN-LAST:event_territoryButton9ActionPerformed

    private void territoryButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton10ActionPerformed
        handleTerritoryClick("Corinth");
    }//GEN-LAST:event_territoryButton10ActionPerformed

    private void territoryButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton11ActionPerformed
        handleTerritoryClick("Crete");
    }//GEN-LAST:event_territoryButton11ActionPerformed

    private void territoryButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton12ActionPerformed
        handleTerritoryClick("Olympia");
    }//GEN-LAST:event_territoryButton12ActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed

        if (currentPhase == GamePhase.DRAFT) {
            sendCommand("NEXT_PHASE");
            appendGameLog("Attack phase geçiş isteği gönderildi...");
        } else if (currentPhase == GamePhase.ATTACK) {
            sendCommand("NEXT_PHASE");
            appendGameLog("Fortify phase geçiş isteği gönderildi...");
        } else if (currentPhase == GamePhase.FORTIFY) {
            sendCommand("END_TURN");
            appendGameLog("Turn bitirme isteği gönderildi...");
        }
    }//GEN-LAST:event_actionButtonActionPerformed
    private void setupButtonMap() {
        territoryButtons.put("Olympus", territoryButton1);
        territoryButtons.put("Sparta", territoryButton2);
        territoryButtons.put("Athens", territoryButton3);
        territoryButtons.put("Delphi", territoryButton4);
        territoryButtons.put("Arcadia", territoryButton5);
        territoryButtons.put("Troy", territoryButton6);
        territoryButtons.put("Elysium", territoryButton7);
        territoryButtons.put("Mycenae", territoryButton8);
        territoryButtons.put("Rhodes", territoryButton9);
        territoryButtons.put("Corinth", territoryButton10);
        territoryButtons.put("Crete", territoryButton11);
        territoryButtons.put("Olympia", territoryButton12);
    }

    private void initializeGameScreen() {
        currentPhase = GamePhase.WAITING_FOR_PLAYERS;
        remainingDraftTroops = 0;
        actionButton.setText("Waiting");
        actionButton.setEnabled(false);

        troopCounts.clear();
        territoryOwners.clear();

        updateStatusArea();
        updateTerritoryTexts();
        updateTerritoryColors();
    }

    public void startGameScreen() {
        initializeGameScreen();
    }

    public void setCurrentPlayer(String playerName) {
        this.currentPlayer = playerName;
    }

    private void clearSelection() {
        fromTerritory = null;
        toTerritory = null;
    }

    private boolean isMyTerritory(String territoryName) {
        String owner = territoryOwners.get(territoryName);
        return currentPlayer.equals(owner);
    }

    private boolean isMyTurn() {
        return actionButton.isEnabled()
                && !actionButton.getText().equals("Opponent Turn")
                && !actionButton.getText().equals("Waiting");
    }

    private void handleTerritoryClick(String territoryName) {

        if (!isMyTurn()) {
            appendGameLog("It is not your turn.");
            return;
        }

        selectedTerritory = territoryName;

        if (currentPhase == GamePhase.DRAFT) {
            draftOneTroop(territoryName);
        } else if (currentPhase == GamePhase.ATTACK) {

            if (fromTerritory == null) {

                if (!isMyTerritory(territoryName)) {
                    appendGameLog("You must select your own territory to attack from.");
                    return;
                }

                fromTerritory = territoryName;
                appendGameLog("Attacker selected: " + fromTerritory);
            } else {

                String attackerOwner = territoryOwners.get(fromTerritory);
                String defenderOwner = territoryOwners.get(territoryName);

                if (attackerOwner.equals(defenderOwner)) {
                    appendGameLog("You cannot attack your own territory.");
                    return;
                }

                toTerritory = territoryName;
                appendGameLog("Defender selected: " + toTerritory);
                sendCommand("ATTACK " + fromTerritory + " " + toTerritory);
                appendGameLog("Attack request sent: " + fromTerritory + " -> " + toTerritory);

                clearSelection();
            }
        } else if (currentPhase == GamePhase.FORTIFY) {
            if (fromTerritory == null) {
                if (!isMyTerritory(territoryName)) {
                    appendGameLog("You must select your own territory to fortify from.");
                    return;
                }

                int troops = troopCounts.getOrDefault(territoryName, 0);

                if (troops <= 1) {
                    appendGameLog("You need at least 2 troops in this territory to fortify from.");
                    return;
                }
                fromTerritory = territoryName;
                appendGameLog("Fortify from: " + fromTerritory);

            } else {
                if (!isMyTerritory(territoryName)) {
                    appendGameLog("You must select your own territory to fortify to.");
                    return;
                }

                toTerritory = territoryName;
                appendGameLog("Fortify to: " + toTerritory);

                String amountText = javax.swing.JOptionPane.showInputDialog(
                        this,
                        "How many troops do you want to move?",
                        "Fortify",
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (amountText == null || amountText.trim().isEmpty()) {
                    appendGameLog("Fortify cancelled.");
                    clearSelection();
                    updateStatusArea();
                    return;
                }

                try {
                    int amount = Integer.parseInt(amountText.trim());

                    sendCommand("FORTIFY " + fromTerritory + " " + toTerritory + " " + amount);
                    appendGameLog("Fortify request sent: "
                            + fromTerritory + " -> " + toTerritory
                            + " troops: " + amount);

                } catch (NumberFormatException e) {
                    appendGameLog("Invalid troop amount.");
                }

                clearSelection();
            }

        }

        updateStatusArea();
    }

    private void draftOneTroop(String territoryName) {
        if (remainingDraftTroops <= 0) {
            appendGameLog("All draft troops placed. Click Go To Attack Phase.");
            return;
        }
        if (!isMyTerritory(territoryName)) {
            appendGameLog("You can only draft troops to your own territories.");
            return;
        }

        sendCommand("DRAFT " + territoryName + " 1");
        appendGameLog("Draft request sent for: " + territoryName);
    }

    private void updateStatusArea() {
        statusArea.setText(
                "You are: " + currentPlayer + "\n"
                + "Current Turn: " + currentTurnPlayer + "\n"
                + "Phase: " + currentPhase + "\n"
                + "Remaining Draft Troops: " + remainingDraftTroops + "\n"
                + "Selected Territory: " + selectedTerritory + "\n"
                + "From: " + fromTerritory + "\n"
                + "To: " + toTerritory
        );
    }

    private void updateTerritoryTexts() {
        for (String territoryName : territoryButtons.keySet()) {
            javax.swing.JButton btn = territoryButtons.get(territoryName);
            String owner = territoryOwners.getOrDefault(territoryName, "NONE");
            Integer troops = troopCounts.getOrDefault(territoryName, 0);
            btn.setText("<html><center>" + territoryName + "<br>(" + owner + ")<br>Troops: " + troops + "</center></html>");
        }
    }

    private void updateTerritoryColors() {
        for (Map.Entry<String, String> entry : territoryOwners.entrySet()) {
            String territoryName = entry.getKey();
            String owner = entry.getValue();
            javax.swing.JButton btn = territoryButtons.get(territoryName);

            if (btn != null) {
                btn.setOpaque(true);
                btn.setContentAreaFilled(true);
                btn.setBorderPainted(true);

                if (owner.equals("NONE") || owner.isEmpty()) {
                    btn.setBackground(java.awt.Color.LIGHT_GRAY);
                } else {

                    if (!playerColors.containsKey(owner)) {
                        int colorIndex = playerColors.size() % defaultColors.length;
                        playerColors.put(owner, defaultColors[colorIndex]);
                    }

                    btn.setBackground(playerColors.get(owner));
                }
            }
        }
    }

    public void setPrintWriter(java.io.PrintWriter out) {
        this.out = out;
    }

    private void sendCommand(String command) {
        if (out != null) {
            out.println(command);
            out.flush();
        } else {
            appendGameLog("Hata: Sunucu bağlantısı yok!");
        }
    }

    public void updateMapFromServer(String mapData) {
        String[] territories = mapData.split("\\|");

        for (String tInfo : territories) {
            String[] parts = tInfo.split(":");

            if (parts.length == 3) {
                String name = parts[0];
                String owner = parts[1];

                try {
                    int troops = Integer.parseInt(parts[2]);
                    territoryOwners.put(name, owner);
                    troopCounts.put(name, troops);
                } catch (NumberFormatException e) {
                    appendGameLog("Map data could not be read for: " + tInfo);

                }
            }
        }

        updateTerritoryTexts();
        updateTerritoryColors();
    }

    public void appendGameLog(String message) {
        gameLogArea.append(message + "\n");
        gameLogArea.setCaretPosition(gameLogArea.getDocument().getLength());
    }

    private void showGameOverScreen(String message) {

        String winnerName = message.replace("GAME_OVER Winner: ", "").trim();

        javax.swing.SwingUtilities.invokeLater(() -> {

            this.dispose();

            EndFrame endFrame = new EndFrame();

            endFrame.setWinner(winnerName);

            endFrame.setLocationRelativeTo(null);
            endFrame.setVisible(true);

            endFrame.setReplayAction(() -> {
                sendCommand("RESET_GAME");
            });

            endFrame.setExitAction(() -> {
                sendCommand("RESET_GAME");
                System.exit(0);
            });
        });
    }

    public void handleServerResponse(String response) {
        appendCleanServerResponse(response);

        if (response.startsWith("DRAFT_NOT_FINISHED")) {
            appendGameLog("Önce bütün draft askerlerini yerleştirmelisin.");
        } else if (response.equals("WAITING_FOR_PLAYERS")) {
            appendGameLog("İkinci oyuncu bekleniyor.");
        } else if (response.startsWith("OPPONENT_DISCONNECTED")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Opponent disconnected. Returning to start screen.",
                    "Opponent Disconnected",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            this.dispose();

            StartFrame startFrame = new StartFrame();
            startFrame.setTitle("Ancient Greek Risk Game");
            startFrame.setLocationRelativeTo(null);
            startFrame.setResizable(false);
            startFrame.setVisible(true);

            return;
        } else if (response.startsWith("GAME_OVER")) {
            showGameOverScreen(response);
        }

        updateStatusArea();
    }

    private void appendCleanServerResponse(String response) {
        if (response.startsWith("OPPONENT_DISCONNECTED")) {
            return;
        }

        if (response.startsWith("DRAFT_SUCCESS")) {
            appendGameLog(response.replace("DRAFT_SUCCESS ", ""));
            return;
        }

        if (response.startsWith("ATTACK_RESULT")) {
            updateDiceLabel(response);
            appendGameLog(extractActionText(response, "ATTACK_RESULT"));
            return;
        }

        if (response.startsWith("TERRITORY_CAPTURED")) {
            updateDiceLabel(response);
            appendGameLog(extractActionText(response, "TERRITORY_CAPTURED"));
            return;
        }

        if (response.startsWith("PHASE_ATTACK")) {
            appendGameLog(currentTurnPlayer + ": Attack phase started.");
            return;
        }

        if (response.startsWith("PHASE_FORTIFY")) {
            appendGameLog(currentTurnPlayer + ": Fortify phase started.");
            return;
        }

        if (response.startsWith("FORTIFY_SUCCESS")) {
            appendGameLog(response.replace("FORTIFY_SUCCESS ", ""));
            return;
        }

        if (response.startsWith("TURN ")) {
            appendGameLog(response);
            return;
        }

        if (response.startsWith("DRAFT_NOT_FINISHED")) {
            return;
        }

        appendGameLog(response);
    }

    private String extractActionText(String response, String prefix) {
        String actionText = response.substring(prefix.length()).trim();
        int diceIndex = actionText.indexOf("Attacker dice:");

        if (diceIndex >= 0) {
            actionText = actionText.substring(0, diceIndex).trim();
        }

        return actionText;
    }

    public void updateGameFromServer(String gameData) {
        String[] parts = gameData.split(";", 4);

        if (parts.length != 4) {
            appendGameLog("Game data could not be read.");
            return;
        }

        try {
            GamePhase serverPhase = GamePhase.valueOf(parts[0]);
            currentTurnPlayer = parts[1];
            int draftTroops = Integer.parseInt(parts[2]);
            String mapData = parts[3];

            currentPhase = serverPhase;
            remainingDraftTroops = draftTroops;
            clearSelection();

            if (currentPhase == GamePhase.ATTACK) {
                diceLabel.setVisible(true);
            } else {
                diceLabel.setText("Waiting for battle...");
                diceLabel.setVisible(false);
            }

            updateMapFromServer(mapData);
            updateActionButton(currentTurnPlayer);
            updateStatusArea();
        } catch (IllegalArgumentException e) {
            appendGameLog("Game data could not be read.");
        }

    }

    private void updateActionButton(String currentTurnPlayer) {
        if (currentPhase == GamePhase.WAITING_FOR_PLAYERS) {
            actionButton.setText("Waiting");
            actionButton.setEnabled(false);
        } else if (!currentPlayer.equals(currentTurnPlayer)) {
            actionButton.setText("Opponent Turn");
            actionButton.setEnabled(false);
        } else {
            actionButton.setEnabled(true);

            if (currentPhase == GamePhase.DRAFT) {
                actionButton.setText("Go To Attack Phase");
            } else if (currentPhase == GamePhase.ATTACK) {
                actionButton.setText("Go To Fortify Phase");
            } else if (currentPhase == GamePhase.FORTIFY) {
                actionButton.setText("End Turn");
            }
        }
    }

    private void updateDiceLabel(String response) {
        if (!response.contains("Attacker dice:") || !response.contains("Defender dice:")) {
            return;
        }

        String attackerPart = response.substring(
                response.indexOf("Attacker dice:"),
                response.indexOf(" Defender dice:")
        );

        String defenderPart;

        if (response.contains(" | ")) {
            defenderPart = response.substring(
                    response.indexOf("Defender dice:"),
                    response.indexOf(" | ")
            );
        } else {
            defenderPart = response.substring(response.indexOf("Defender dice:"));
        }

        diceLabel.setVisible(true);
        diceLabel.setText("<html><center>⚔ Dice Battle ⚔<br>"
                + attackerPart + "<br>"
                + defenderPart
                + "</center></html>");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel diceLabel;
    private javax.swing.JTextArea gameLogArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JButton territoryButton1;
    private javax.swing.JButton territoryButton10;
    private javax.swing.JButton territoryButton11;
    private javax.swing.JButton territoryButton12;
    private javax.swing.JButton territoryButton2;
    private javax.swing.JButton territoryButton3;
    private javax.swing.JButton territoryButton4;
    private javax.swing.JButton territoryButton5;
    private javax.swing.JButton territoryButton6;
    private javax.swing.JButton territoryButton7;
    private javax.swing.JButton territoryButton8;
    private javax.swing.JButton territoryButton9;
    // End of variables declaration//GEN-END:variables
}
