/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.riskgame.gui;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author elifnur
 */
public class GameFrame extends javax.swing.JFrame {

    private String selectedTerritory = null;
    private String currentPhase = "DRAFT";
    private int remainingDraftTroops = 3;
    private String fromTerritory = null;
    private String toTerritory = null;
    private String currentPlayer = "Player1";
    private Map<String, String> territoryOwners = new HashMap<>();

    private Map<String, Integer> troopCounts = new HashMap<>();

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        initializeGameScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        territoryButton1 = new javax.swing.JButton();
        territoryButton2 = new javax.swing.JButton();
        territoryButton3 = new javax.swing.JButton();
        territoryButton4 = new javax.swing.JButton();
        territoryButton5 = new javax.swing.JButton();
        territoryButton6 = new javax.swing.JButton();
        territoryButton7 = new javax.swing.JButton();
        territoryButton8 = new javax.swing.JButton();
        territoryButton9 = new javax.swing.JButton();
        territoryButton10 = new javax.swing.JButton();
        territoryButton11 = new javax.swing.JButton();
        territoryButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameLogArea = new javax.swing.JTextArea();
        actionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        territoryButton1.setText("Olympus");
        territoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 140));

        territoryButton2.setText("Sparta");
        territoryButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 140));

        territoryButton3.setText("Athens");
        territoryButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 140));

        territoryButton4.setText("Delphi");
        territoryButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 240, 60));

        territoryButton5.setText("Arcadia");
        territoryButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, 140));

        territoryButton6.setText("Troy");
        territoryButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 140));

        territoryButton7.setText("Elysium");
        territoryButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, 140));

        territoryButton8.setText("Mycenae");
        territoryButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, 140));

        territoryButton9.setText("Rhodes");
        territoryButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 140));

        territoryButton10.setText("Corinth");
        territoryButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 160, 60));

        territoryButton11.setText("Crete");
        territoryButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 80, 140));

        territoryButton12.setText("Olympia");
        territoryButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, 200));

        jButton13.setText("jButton13");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dice-cube.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 410, 120, 110));

        statusArea.setColumns(20);
        statusArea.setRows(5);
        jScrollPane1.setViewportView(statusArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 360, 120));

        gameLogArea.setColumns(20);
        gameLogArea.setRows(5);
        jScrollPane2.setViewportView(gameLogArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 360, 110));

        actionButton.setText("jButton14");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(actionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 420, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jLabel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void territoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton1ActionPerformed
        handleTerritoryClick("Olympus");
    }//GEN-LAST:event_territoryButton1ActionPerformed

    private void territoryButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton2ActionPerformed
        handleTerritoryClick("Sparta");
    }//GEN-LAST:event_territoryButton2ActionPerformed

    private void territoryButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton3ActionPerformed
        handleTerritoryClick("Athens");
    }//GEN-LAST:event_territoryButton3ActionPerformed

    private void territoryButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton4ActionPerformed
        handleTerritoryClick("Delphi");
    }//GEN-LAST:event_territoryButton4ActionPerformed

    private void territoryButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton5ActionPerformed
        handleTerritoryClick("Arcadia");
    }//GEN-LAST:event_territoryButton5ActionPerformed

    private void territoryButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton6ActionPerformed
        handleTerritoryClick("Troy");
    }//GEN-LAST:event_territoryButton6ActionPerformed

    private void territoryButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton7ActionPerformed
        handleTerritoryClick("Elysium");
    }//GEN-LAST:event_territoryButton7ActionPerformed

    private void territoryButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton8ActionPerformed
        handleTerritoryClick("Mycenae");
    }//GEN-LAST:event_territoryButton8ActionPerformed

    private void territoryButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton9ActionPerformed
        handleTerritoryClick("Rhodes");
    }//GEN-LAST:event_territoryButton9ActionPerformed

    private void territoryButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton10ActionPerformed
        handleTerritoryClick("Corinth");
    }//GEN-LAST:event_territoryButton10ActionPerformed

    private void territoryButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton11ActionPerformed
        handleTerritoryClick("Crete");
    }//GEN-LAST:event_territoryButton11ActionPerformed

    private void territoryButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton12ActionPerformed
        handleTerritoryClick("Olympia");
    }//GEN-LAST:event_territoryButton12ActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        if (currentPhase.equals("DRAFT")) {

            if (remainingDraftTroops > 0) {
                gameLogArea.append("You must place all draft troops first.\n");
                return;
            }

            currentPhase = "ATTACK";
            actionButton.setText("Attack / Go To Fortify");
            fromTerritory = null;
            toTerritory = null;

            gameLogArea.append("Phase changed to ATTACK.\n");
            updateStatusArea();
            return;
        }

        if (currentPhase.equals("ATTACK")) {

            if (fromTerritory == null || toTerritory == null) {
                currentPhase = "FORTIFY";
                actionButton.setText("Fortify / End Turn");
                gameLogArea.append("Phase changed to FORTIFY.\n");
                updateStatusArea();
                return;
            }

            gameLogArea.append(fromTerritory + " attacks " + toTerritory + "\n");

            fromTerritory = null;
            toTerritory = null;

            updateStatusArea();
            return;
        }

        if (currentPhase.equals("FORTIFY")) {

            if (fromTerritory == null || toTerritory == null) {
                currentPhase = "DRAFT";
                actionButton.setText("Place Troops");
                remainingDraftTroops = 3;
                gameLogArea.append("Turn ended. New draft phase started.\n");
                updateStatusArea();
                return;
            }

            gameLogArea.append("Fortify from " + fromTerritory + " to " + toTerritory + "\n");

            fromTerritory = null;
            toTerritory = null;

            updateStatusArea();
        }
    }//GEN-LAST:event_actionButtonActionPerformed

    private void initializeGameScreen() {
        currentPhase = "DRAFT";
        remainingDraftTroops = 3;
        troopCounts.put("Olympus", 0);
        troopCounts.put("Sparta", 0);
        troopCounts.put("Athens", 0);
        troopCounts.put("Delphi", 0);
        troopCounts.put("Arcadia", 0);
        troopCounts.put("Troy", 0);
        troopCounts.put("Elysium", 0);
        troopCounts.put("Mycenae", 0);
        troopCounts.put("Rhodes", 0);
        troopCounts.put("Corinth", 0);
        troopCounts.put("Crete", 0);
        troopCounts.put("Olympia", 0);

        actionButton.setText("Go To Attack Phase");

        updateStatusArea();
        updateTerritoryTexts();
        initializeOwners();
        updateTerritoryColors();
    }

    private void handleTerritoryClick(String territoryName) {

        selectedTerritory = territoryName;

        if (currentPhase.equals("DRAFT")) {
            draftOneTroop(territoryName);
        } else if (currentPhase.equals("ATTACK")) {

            if (fromTerritory == null) {

                String owner = territoryOwners.get(territoryName);

                if (!currentPlayer.equals(owner)) {
                    gameLogArea.append("You must select your own territory to attack from.\n");
                    return;
                }

                fromTerritory = territoryName;
                gameLogArea.append("Attacker selected: " + fromTerritory + "\n");
            } else {

                String attackerOwner = territoryOwners.get(fromTerritory);
                String defenderOwner = territoryOwners.get(territoryName);

                if (attackerOwner.equals(defenderOwner)) {
                    gameLogArea.append("You cannot attack your own territory.\n");
                    return;
                }

                toTerritory = territoryName;
                gameLogArea.append("Defender selected: " + toTerritory + "\n");
            }
        } else if (currentPhase.equals("FORTIFY")) {

            if (fromTerritory == null) {
                fromTerritory = territoryName;
                gameLogArea.append("Fortify from: " + fromTerritory + "\n");
            } else {
                toTerritory = territoryName;
                gameLogArea.append("Fortify to: " + toTerritory + "\n");
            }
        }

        updateStatusArea();
    }

    private void draftOneTroop(String territoryName) {
        String owner = territoryOwners.get(territoryName);

        if (!currentPlayer.equals(owner)) {
            gameLogArea.append("You can only draft to your own territories.\n");
            return;
        }
        if (remainingDraftTroops <= 0) {
            gameLogArea.append("All draft troops placed. Click Go To Attack Phase.\n");
            return;
        }

        // Şimdilik server bağlanmadan test ediyoruz.
        // Sonra burası sendCommand("DRAFT " + territoryName + " 1") olacak.
        remainingDraftTroops--;

        int currentTroops = troopCounts.getOrDefault(territoryName, 0);
        troopCounts.put(territoryName, currentTroops + 1);
        updateTerritoryTexts();

        gameLogArea.append("Placed 1 troop to " + territoryName + "\n");

        if (remainingDraftTroops == 0) {
            gameLogArea.append("Draft finished. You can go to attack phase.\n");
        }
    }

    private void updateStatusArea() {
        statusArea.setText(
                "Phase: " + currentPhase + "\n"
                + "Remaining Draft Troops: " + remainingDraftTroops + "\n"
                + "Selected Territory: " + selectedTerritory + "\n"
                + "From: " + fromTerritory + "\n"
                + "To: " + toTerritory
        );
    }

    private void updateTerritoryTexts() {

        territoryButton1.setText(
                "<html><center>Olympus<br>"
                + troopCounts.get("Olympus")
                + "</center></html>"
        );

        territoryButton2.setText(
                "<html><center>Sparta<br>"
                + troopCounts.get("Sparta")
                + "</center></html>"
        );

        territoryButton3.setText(
                "<html><center>Athens<br>"
                + troopCounts.get("Athens")
                + "</center></html>"
        );

        territoryButton4.setText(
                "<html><center>Delphi<br>"
                + troopCounts.get("Delphi")
                + "</center></html>"
        );
    }

    private void initializeOwners() {
        territoryOwners.put("Olympus", "Player1");
        territoryOwners.put("Sparta", "Player2");
        territoryOwners.put("Athens", "Player1");
        territoryOwners.put("Troy", "Player2");

        // Diğer territoryleri de aynı mantıkla ekle
    }

    private java.awt.Color getOwnerColor(String owner) {
        if ("Player1".equals(owner)) {
            return new java.awt.Color(150, 40, 40); // kırmızı
        }

        if ("Player2".equals(owner)) {
            return new java.awt.Color(40, 80, 160); // mavi
        }

        return java.awt.Color.LIGHT_GRAY;
    }

    private void updateTerritoryColors() {
        territoryButton1.setBackground(getOwnerColor(territoryOwners.get("Olympus")));
        territoryButton2.setBackground(getOwnerColor(territoryOwners.get("Sparta")));
        territoryButton3.setBackground(getOwnerColor(territoryOwners.get("Athens")));
        territoryButton4.setBackground(getOwnerColor(territoryOwners.get("Elphi")));

        territoryButton1.setForeground(java.awt.Color.WHITE);
        territoryButton2.setForeground(java.awt.Color.WHITE);
        territoryButton3.setForeground(java.awt.Color.WHITE);
        territoryButton4.setForeground(java.awt.Color.WHITE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JTextArea gameLogArea;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JButton territoryButton1;
    private javax.swing.JButton territoryButton10;
    private javax.swing.JButton territoryButton11;
    private javax.swing.JButton territoryButton12;
    private javax.swing.JButton territoryButton2;
    private javax.swing.JButton territoryButton3;
    private javax.swing.JButton territoryButton4;
    private javax.swing.JButton territoryButton5;
    private javax.swing.JButton territoryButton6;
    private javax.swing.JButton territoryButton7;
    private javax.swing.JButton territoryButton8;
    private javax.swing.JButton territoryButton9;
    // End of variables declaration//GEN-END:variables
}
