/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.riskgame.gui;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author elifnur
 */
public class GameFrame extends javax.swing.JFrame {

    private java.io.PrintWriter out;
    private String currentPhase = "DRAFT";
    private int remainingDraftTroops = 3;
    private String fromTerritory = null;
    private String toTerritory = null;
    private String selectedTerritory;
    private String currentPlayer = "Player1";
    private Map<String, String> territoryOwners = new HashMap<>();

    private Map<String, Integer> troopCounts = new HashMap<>();
    private Map<String, javax.swing.JButton> territoryButtons = new HashMap<>();
    private Map<String, java.awt.Color> playerColors = new HashMap<>();

    private java.awt.Color[] defaultColors = {
        new java.awt.Color(100, 200, 255), 
        new java.awt.Color(255, 150, 150) 
    };

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        setupButtonMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        territoryButton1 = new javax.swing.JButton();
        territoryButton2 = new javax.swing.JButton();
        territoryButton3 = new javax.swing.JButton();
        territoryButton4 = new javax.swing.JButton();
        territoryButton5 = new javax.swing.JButton();
        territoryButton6 = new javax.swing.JButton();
        territoryButton7 = new javax.swing.JButton();
        territoryButton8 = new javax.swing.JButton();
        territoryButton9 = new javax.swing.JButton();
        territoryButton10 = new javax.swing.JButton();
        territoryButton11 = new javax.swing.JButton();
        territoryButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameLogArea = new javax.swing.JTextArea();
        actionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        territoryButton1.setText("Olympus");
        territoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 140));

        territoryButton2.setText("Sparta");
        territoryButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 140));

        territoryButton3.setText("Athens");
        territoryButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 140));

        territoryButton4.setText("Delphi");
        territoryButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 240, 60));

        territoryButton5.setText("Arcadia");
        territoryButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, 140));

        territoryButton6.setText("Troy");
        territoryButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 140));

        territoryButton7.setText("Elysium");
        territoryButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, 140));

        territoryButton8.setText("Mycenae");
        territoryButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, 140));

        territoryButton9.setText("Rhodes");
        territoryButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 140));

        territoryButton10.setText("Corinth");
        territoryButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 160, 60));

        territoryButton11.setText("Crete");
        territoryButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 80, 140));

        territoryButton12.setText("Olympia");
        territoryButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                territoryButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(territoryButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dice-cube.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 410, 120, 110));

        statusArea.setColumns(20);
        statusArea.setRows(5);
        jScrollPane1.setViewportView(statusArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 360, 120));

        gameLogArea.setColumns(20);
        gameLogArea.setRows(5);
        jScrollPane2.setViewportView(gameLogArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 360, 110));

        actionButton.setText("jButton14");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(actionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 420, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jLabel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void territoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton1ActionPerformed
        handleTerritoryClick("Olympus");
    }//GEN-LAST:event_territoryButton1ActionPerformed

    private void territoryButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton2ActionPerformed
        handleTerritoryClick("Sparta");
    }//GEN-LAST:event_territoryButton2ActionPerformed

    private void territoryButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton3ActionPerformed
        handleTerritoryClick("Athens");
    }//GEN-LAST:event_territoryButton3ActionPerformed

    private void territoryButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton4ActionPerformed
        handleTerritoryClick("Delphi");
    }//GEN-LAST:event_territoryButton4ActionPerformed

    private void territoryButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton5ActionPerformed
        handleTerritoryClick("Arcadia");
    }//GEN-LAST:event_territoryButton5ActionPerformed

    private void territoryButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton6ActionPerformed
        handleTerritoryClick("Troy");
    }//GEN-LAST:event_territoryButton6ActionPerformed

    private void territoryButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton7ActionPerformed
        handleTerritoryClick("Elysium");
    }//GEN-LAST:event_territoryButton7ActionPerformed

    private void territoryButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton8ActionPerformed
        handleTerritoryClick("Mycenae");
    }//GEN-LAST:event_territoryButton8ActionPerformed

    private void territoryButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton9ActionPerformed
        handleTerritoryClick("Rhodes");
    }//GEN-LAST:event_territoryButton9ActionPerformed

    private void territoryButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton10ActionPerformed
        handleTerritoryClick("Corinth");
    }//GEN-LAST:event_territoryButton10ActionPerformed

    private void territoryButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton11ActionPerformed
        handleTerritoryClick("Crete");
    }//GEN-LAST:event_territoryButton11ActionPerformed

    private void territoryButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_territoryButton12ActionPerformed
        handleTerritoryClick("Olympia");
    }//GEN-LAST:event_territoryButton12ActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed

        if (currentPhase.equals("DRAFT")) {
            sendCommand("NEXT_PHASE");
            gameLogArea.append("Attack phase geçiş isteği gönderildi...\n");
        } else if (currentPhase.equals("ATTACK")) {
            sendCommand("NEXT_PHASE");
            gameLogArea.append("Fortify phase geçiş isteği gönderildi...\n");
        } else if (currentPhase.equals("FORTIFY")) {
            sendCommand("END_TURN");
            gameLogArea.append("Turn bitirme isteği gönderildi...\n");
        }
    }//GEN-LAST:event_actionButtonActionPerformed
    private void setupButtonMap() {
        territoryButtons.put("Olympus", territoryButton1);
        territoryButtons.put("Sparta", territoryButton2);
        territoryButtons.put("Athens", territoryButton3);
        territoryButtons.put("Delphi", territoryButton4); 
        territoryButtons.put("Arcadia", territoryButton5);
        territoryButtons.put("Troy", territoryButton6);
        territoryButtons.put("Elysium", territoryButton7);
        territoryButtons.put("Mycenae", territoryButton8);
        territoryButtons.put("Rhodes", territoryButton9);
        territoryButtons.put("Corinth", territoryButton10);
        territoryButtons.put("Crete", territoryButton11);
        territoryButtons.put("Olympia", territoryButton12);
    }

    private void initializeGameScreen() {
        currentPhase = "DRAFT";
        remainingDraftTroops = 3;

        troopCounts.clear();
        territoryOwners.clear();

        actionButton.setText("Go To Attack Phase");

        updateStatusArea();
        updateTerritoryTexts();
        updateTerritoryColors();
    }

    public void startGameScreen() {
        initializeGameScreen();
    }

    public void setCurrentPlayer(String playerName) {
        this.currentPlayer = playerName;
    }

    private void handleTerritoryClick(String territoryName) {

        selectedTerritory = territoryName;

        if (currentPhase.equals("DRAFT")) {
            draftOneTroop(territoryName);
        } else if (currentPhase.equals("ATTACK")) {

            if (fromTerritory == null) {

                String owner = territoryOwners.get(territoryName);

                if (!currentPlayer.equals(owner)) {
                    gameLogArea.append("You must select your own territory to attack from.\n");
                    return;
                }

                fromTerritory = territoryName;
                gameLogArea.append("Attacker selected: " + fromTerritory + "\n");
            } else {

                String attackerOwner = territoryOwners.get(fromTerritory);
                String defenderOwner = territoryOwners.get(territoryName);

                if (attackerOwner.equals(defenderOwner)) {
                    gameLogArea.append("You cannot attack your own territory.\n");
                    return;
                }

                toTerritory = territoryName;
                gameLogArea.append("Defender selected: " + toTerritory + "\n");
                sendCommand("ATTACK " + fromTerritory + " " + toTerritory);
                gameLogArea.append("Attack request sent: " + fromTerritory + " -> " + toTerritory + "\n");

                fromTerritory = null;
                toTerritory = null;
            }
        } else if (currentPhase.equals("FORTIFY")) {
            if (fromTerritory == null) {
                String owner = territoryOwners.get(territoryName);

                if (!currentPlayer.equals(owner)) {
                    gameLogArea.append("You must select your own territory to fortify from.\n");
                    return;
                }
                int troops = troopCounts.getOrDefault(territoryName, 0);

                if (troops <= 1) {
                    gameLogArea.append("You need at least 2 troops in this territory to fortify from.\n");
                    return;
                }
                fromTerritory = territoryName;
                gameLogArea.append("Fortify from: " + fromTerritory + "\n");

            } else {
                String owner = territoryOwners.get(territoryName);

                if (!currentPlayer.equals(owner)) {
                    gameLogArea.append("You must select your own territory to fortify to.\n");
                    return;
                }

                toTerritory = territoryName;
                gameLogArea.append("Fortify to: " + toTerritory + "\n");

                String amountText = javax.swing.JOptionPane.showInputDialog(
                        this,
                        "How many troops do you want to move?",
                        "Fortify",
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (amountText == null || amountText.trim().isEmpty()) {
                    gameLogArea.append("Fortify cancelled.\n");
                    fromTerritory = null;
                    toTerritory = null;
                    updateStatusArea();
                    return;
                }

                try {
                    int amount = Integer.parseInt(amountText.trim());

                    sendCommand("FORTIFY " + fromTerritory + " " + toTerritory + " " + amount);
                    gameLogArea.append("Fortify request sent: "
                            + fromTerritory + " -> " + toTerritory
                            + " troops: " + amount + "\n");

                } catch (NumberFormatException e) {
                    gameLogArea.append("Invalid troop amount.\n");
                }

                fromTerritory = null;
                toTerritory = null;
            }

        }

        updateStatusArea();
    }

    private void draftOneTroop(String territoryName) {
        if (remainingDraftTroops <= 0) {
            gameLogArea.append("All draft troops placed. Click Go To Attack Phase.\n");
            return;
        }
        sendCommand("DRAFT " + territoryName + " 1");
        gameLogArea.append("Draft request sent for: " + territoryName + "\n");
    }

    private void updateStatusArea() {
        statusArea.setText(
                "Phase: " + currentPhase + "\n"
                + "Remaining Draft Troops: " + remainingDraftTroops + "\n"
                + "Selected Territory: " + selectedTerritory + "\n"
                + "From: " + fromTerritory + "\n"
                + "To: " + toTerritory
        );
    }

    private void updateTerritoryTexts() {
        for (String territoryName : territoryButtons.keySet()) {
            javax.swing.JButton btn = territoryButtons.get(territoryName);
            String owner = territoryOwners.getOrDefault(territoryName, "NONE");
            Integer troops = troopCounts.getOrDefault(territoryName, 0);
            btn.setText("<html><center>" + territoryName + "<br>(" + owner + ")<br>Troops: " + troops + "</center></html>");
        }
    }

    private void updateTerritoryColors() {
        for (Map.Entry<String, String> entry : territoryOwners.entrySet()) {
            String territoryName = entry.getKey();
            String owner = entry.getValue();
            javax.swing.JButton btn = territoryButtons.get(territoryName);

            if (btn != null) {
                btn.setOpaque(true);
                btn.setContentAreaFilled(true);
                btn.setBorderPainted(true);

                if (owner.equals("NONE") || owner.isEmpty()) {
                    btn.setBackground(java.awt.Color.LIGHT_GRAY);
                } else {
                    
                    if (!playerColors.containsKey(owner)) {
                        int colorIndex = playerColors.size() % defaultColors.length;
                        playerColors.put(owner, defaultColors[colorIndex]);
                    }
                    
                    btn.setBackground(playerColors.get(owner));
                }
            }
        }
    }

    public void setPrintWriter(java.io.PrintWriter out) {
        this.out = out;
    }

    private void sendCommand(String command) {
        if (out != null) {
            out.println(command);
            out.flush();
        } else {
            gameLogArea.append("Hata: Sunucu bağlantısı yok!\n");
        }
    }
    
    public void updateMapFromServer(String mapData) {
        String[] territories = mapData.split("\\|");

        for (String tInfo : territories) {
            String[] parts = tInfo.split(":");

            if (parts.length == 3) {
                String name = parts[0];
                String owner = parts[1];

                try {
                    int troops = Integer.parseInt(parts[2]);
                    territoryOwners.put(name, owner);
                    troopCounts.put(name, troops);
                } catch (NumberFormatException e) {
                    
                }
            }
        }

        updateTerritoryTexts();
        updateTerritoryColors();
    }

    public void appendGameLog(String message) {
        gameLogArea.append(message + "\n");
        gameLogArea.setCaretPosition(gameLogArea.getDocument().getLength());
    }

    public void handleServerResponse(String response) {
        appendGameLog(response);

        if (response.startsWith("DRAFT_SUCCESS")) {
            String[] parts = response.split(": ");

            if (parts.length == 2) {
                try {
                    remainingDraftTroops = Integer.parseInt(parts[1]);
                } catch (NumberFormatException e) {
                    appendGameLog("Draft troop sayısı okunamadı.");
                }
            }

            sendCommand("MAP");
        } else if (response.startsWith("DRAFT_NOT_FINISHED")) {
            appendGameLog("Önce bütün draft askerlerini yerleştirmelisin.");
        } else if (response.equals("PHASE_ATTACK")) {
            currentPhase = "ATTACK";
            fromTerritory = null;
            toTerritory = null;
            actionButton.setText("Go To Fortify Phase");
            appendGameLog("Attack phase başladı.");
        } else if (response.equals("PHASE_FORTIFY")) {
            currentPhase = "FORTIFY";
            fromTerritory = null;
            toTerritory = null;
            actionButton.setText("End Turn");
            appendGameLog("Fortify phase başladı.");
        } else if (response.startsWith("TURN ")) {
            currentPhase = "DRAFT";
            remainingDraftTroops = 3;
            fromTerritory = null;
            toTerritory = null;
            actionButton.setText("Go To Attack Phase");
            appendGameLog("Sıra: " + response.substring(5));
            sendCommand("MAP");
        } else if (response.startsWith("ATTACK_RESULT")
                || response.equals("TERRITORY_CAPTURED")
                || response.equals("BLITZ_SUCCESS")) {
            fromTerritory = null;
            toTerritory = null;
            sendCommand("MAP");
        } else if (response.equals("FORTIFY_SUCCESS")) {
            fromTerritory = null;
            toTerritory = null;
            sendCommand("MAP");
        } else if (response.startsWith("GAME_OVER")) {
            javax.swing.JOptionPane.showMessageDialog(this, response);
        }

        updateStatusArea();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JTextArea gameLogArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JButton territoryButton1;
    private javax.swing.JButton territoryButton10;
    private javax.swing.JButton territoryButton11;
    private javax.swing.JButton territoryButton12;
    private javax.swing.JButton territoryButton2;
    private javax.swing.JButton territoryButton3;
    private javax.swing.JButton territoryButton4;
    private javax.swing.JButton territoryButton5;
    private javax.swing.JButton territoryButton6;
    private javax.swing.JButton territoryButton7;
    private javax.swing.JButton territoryButton8;
    private javax.swing.JButton territoryButton9;
    // End of variables declaration//GEN-END:variables
}
